apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chore-quest.fullname" . }}-data
  labels:
    app: chore-quest
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.size }}
